import { useEffect, useState } from 'react'
import { CheckCircle2, Workflow, XCircle } from 'lucide-react'
import { getNotificationStatus } from '../api/api'
import EmptyState from '../components/EmptyState'

function Notifications() {
  const [status, setStatus] = useState(null)
  useEffect(() => { getNotificationStatus().then(setStatus).catch(() => setStatus({ error: true })) }, [])
  if (!status) return <EmptyState title="Loading notification status..." message="Checking the local n8n integration contract." />
  if (status.error) return <EmptyState title="Backend unavailable" message="Notification status needs the local FastAPI service." />
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-wide text-sentinel-teal">Workflow control</p><h1 className="mt-1 text-2xl font-semibold text-sentinel-ink">Notifications</h1><p className="mt-1 text-sm text-slate-600">External delivery is reported honestly; this UI never invents a successful send.</p></div><section className="rounded-lg border border-slate-200 bg-sentinel-card p-5 shadow-sm"><div className="flex items-start gap-3">{status.configured ? <CheckCircle2 className="h-6 w-6 text-sentinel-teal" /> : <XCircle className="h-6 w-6 text-slate-400" />}<div><h2 className="text-lg font-semibold text-sentinel-ink">{status.configured ? 'Webhook configured' : 'n8n runtime not connected'}</h2><p className="mt-1 text-sm text-slate-600">{status.message}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-md bg-sentinel-mist p-3"><p className="text-xs text-slate-500">Runtime</p><p className="mt-1 font-medium">{status.runtime}</p></div><div className="rounded-md bg-sentinel-mist p-3"><p className="text-xs text-slate-500">Webhook state</p><p className="mt-1 font-medium">{status.webhook_configured ? 'Configured' : 'Not configured'}</p></div><div className="rounded-md bg-sentinel-mist p-3"><p className="text-xs text-slate-500">Last execution</p><p className="mt-1 font-medium">{status.last_execution || 'Not observed locally'}</p></div></div></section><section className="rounded-lg border border-slate-200 bg-sentinel-card p-5 shadow-sm"><div className="flex items-center gap-2"><Workflow className="h-5 w-5 text-sentinel-teal" /><h2 className="text-base font-semibold text-sentinel-ink">Alert-to-notification flow</h2></div><div className="mt-4 flex flex-wrap items-center gap-2 text-sm text-slate-600"><span className="rounded-md bg-sentinel-mist px-3 py-2">Risk engine</span><span>→</span><span className="rounded-md bg-sentinel-mist px-3 py-2">FastAPI open alerts</span><span>→</span><span className="rounded-md bg-sentinel-mist px-3 py-2">n8n poll</span><span>→</span><span className="rounded-md bg-sentinel-mist px-3 py-2">Demo receiver</span></div><p className="mt-4 text-xs text-slate-500">Synthetic aggregate payloads only. See n8n/README.md for environment configuration.</p></section></div>
}

export default Notifications
